name: Android Lib SmokeTest

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: mac-m1
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      - name: Setup Android SDK
        uses: nttld/setup-ndk@v1
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run SmokeTest
        run: |
          ./gradlew app:connectedFdroidAndroidTest
